//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.WS_Piloto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Piloto.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplication4.WS_Piloto.HelloWorldResponse HelloWorld(WebApplication4.WS_Piloto.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication4.WS_Piloto.HelloWorldResponse> HelloWorldAsync(WebApplication4.WS_Piloto.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarPiloto", ReplyAction="*")]
        WebApplication4.WS_Piloto.AgregarPilotoResponse AgregarPiloto(WebApplication4.WS_Piloto.AgregarPilotoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarPiloto", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication4.WS_Piloto.AgregarPilotoResponse> AgregarPilotoAsync(WebApplication4.WS_Piloto.AgregarPilotoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento FinalizarViajeResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinalizarViaje", ReplyAction="*")]
        WebApplication4.WS_Piloto.FinalizarViajeResponse FinalizarViaje(WebApplication4.WS_Piloto.FinalizarViajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinalizarViaje", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication4.WS_Piloto.FinalizarViajeResponse> FinalizarViajeAsync(WebApplication4.WS_Piloto.FinalizarViajeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Piloto.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplication4.WS_Piloto.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Piloto.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplication4.WS_Piloto.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarPilotoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarPiloto", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Piloto.AgregarPilotoRequestBody Body;
        
        public AgregarPilotoRequest() {
        }
        
        public AgregarPilotoRequest(WebApplication4.WS_Piloto.AgregarPilotoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarPilotoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string linea;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string placa;
        
        public AgregarPilotoRequestBody() {
        }
        
        public AgregarPilotoRequestBody(string name, string tel, string marca, string linea, string placa) {
            this.name = name;
            this.tel = tel;
            this.marca = marca;
            this.linea = linea;
            this.placa = placa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarPilotoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarPilotoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Piloto.AgregarPilotoResponseBody Body;
        
        public AgregarPilotoResponse() {
        }
        
        public AgregarPilotoResponse(WebApplication4.WS_Piloto.AgregarPilotoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarPilotoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgregarPilotoResult;
        
        public AgregarPilotoResponseBody() {
        }
        
        public AgregarPilotoResponseBody(string AgregarPilotoResult) {
            this.AgregarPilotoResult = AgregarPilotoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizarViajeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizarViaje", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Piloto.FinalizarViajeRequestBody Body;
        
        public FinalizarViajeRequest() {
        }
        
        public FinalizarViajeRequest(WebApplication4.WS_Piloto.FinalizarViajeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FinalizarViajeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idPiloto;
        
        public FinalizarViajeRequestBody() {
        }
        
        public FinalizarViajeRequestBody(int idPiloto) {
            this.idPiloto = idPiloto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizarViajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizarViajeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Piloto.FinalizarViajeResponseBody Body;
        
        public FinalizarViajeResponse() {
        }
        
        public FinalizarViajeResponse(WebApplication4.WS_Piloto.FinalizarViajeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FinalizarViajeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FinalizarViajeResult;
        
        public FinalizarViajeResponseBody() {
        }
        
        public FinalizarViajeResponseBody(string FinalizarViajeResult) {
            this.FinalizarViajeResult = FinalizarViajeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication4.WS_Piloto.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication4.WS_Piloto.WebService1Soap>, WebApplication4.WS_Piloto.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication4.WS_Piloto.HelloWorldResponse WebApplication4.WS_Piloto.WebService1Soap.HelloWorld(WebApplication4.WS_Piloto.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplication4.WS_Piloto.HelloWorldRequest inValue = new WebApplication4.WS_Piloto.HelloWorldRequest();
            inValue.Body = new WebApplication4.WS_Piloto.HelloWorldRequestBody();
            WebApplication4.WS_Piloto.HelloWorldResponse retVal = ((WebApplication4.WS_Piloto.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication4.WS_Piloto.HelloWorldResponse> WebApplication4.WS_Piloto.WebService1Soap.HelloWorldAsync(WebApplication4.WS_Piloto.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication4.WS_Piloto.HelloWorldResponse> HelloWorldAsync() {
            WebApplication4.WS_Piloto.HelloWorldRequest inValue = new WebApplication4.WS_Piloto.HelloWorldRequest();
            inValue.Body = new WebApplication4.WS_Piloto.HelloWorldRequestBody();
            return ((WebApplication4.WS_Piloto.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication4.WS_Piloto.AgregarPilotoResponse WebApplication4.WS_Piloto.WebService1Soap.AgregarPiloto(WebApplication4.WS_Piloto.AgregarPilotoRequest request) {
            return base.Channel.AgregarPiloto(request);
        }
        
        public string AgregarPiloto(string name, string tel, string marca, string linea, string placa) {
            WebApplication4.WS_Piloto.AgregarPilotoRequest inValue = new WebApplication4.WS_Piloto.AgregarPilotoRequest();
            inValue.Body = new WebApplication4.WS_Piloto.AgregarPilotoRequestBody();
            inValue.Body.name = name;
            inValue.Body.tel = tel;
            inValue.Body.marca = marca;
            inValue.Body.linea = linea;
            inValue.Body.placa = placa;
            WebApplication4.WS_Piloto.AgregarPilotoResponse retVal = ((WebApplication4.WS_Piloto.WebService1Soap)(this)).AgregarPiloto(inValue);
            return retVal.Body.AgregarPilotoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication4.WS_Piloto.AgregarPilotoResponse> WebApplication4.WS_Piloto.WebService1Soap.AgregarPilotoAsync(WebApplication4.WS_Piloto.AgregarPilotoRequest request) {
            return base.Channel.AgregarPilotoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication4.WS_Piloto.AgregarPilotoResponse> AgregarPilotoAsync(string name, string tel, string marca, string linea, string placa) {
            WebApplication4.WS_Piloto.AgregarPilotoRequest inValue = new WebApplication4.WS_Piloto.AgregarPilotoRequest();
            inValue.Body = new WebApplication4.WS_Piloto.AgregarPilotoRequestBody();
            inValue.Body.name = name;
            inValue.Body.tel = tel;
            inValue.Body.marca = marca;
            inValue.Body.linea = linea;
            inValue.Body.placa = placa;
            return ((WebApplication4.WS_Piloto.WebService1Soap)(this)).AgregarPilotoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication4.WS_Piloto.FinalizarViajeResponse WebApplication4.WS_Piloto.WebService1Soap.FinalizarViaje(WebApplication4.WS_Piloto.FinalizarViajeRequest request) {
            return base.Channel.FinalizarViaje(request);
        }
        
        public string FinalizarViaje(int idPiloto) {
            WebApplication4.WS_Piloto.FinalizarViajeRequest inValue = new WebApplication4.WS_Piloto.FinalizarViajeRequest();
            inValue.Body = new WebApplication4.WS_Piloto.FinalizarViajeRequestBody();
            inValue.Body.idPiloto = idPiloto;
            WebApplication4.WS_Piloto.FinalizarViajeResponse retVal = ((WebApplication4.WS_Piloto.WebService1Soap)(this)).FinalizarViaje(inValue);
            return retVal.Body.FinalizarViajeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication4.WS_Piloto.FinalizarViajeResponse> WebApplication4.WS_Piloto.WebService1Soap.FinalizarViajeAsync(WebApplication4.WS_Piloto.FinalizarViajeRequest request) {
            return base.Channel.FinalizarViajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication4.WS_Piloto.FinalizarViajeResponse> FinalizarViajeAsync(int idPiloto) {
            WebApplication4.WS_Piloto.FinalizarViajeRequest inValue = new WebApplication4.WS_Piloto.FinalizarViajeRequest();
            inValue.Body = new WebApplication4.WS_Piloto.FinalizarViajeRequestBody();
            inValue.Body.idPiloto = idPiloto;
            return ((WebApplication4.WS_Piloto.WebService1Soap)(this)).FinalizarViajeAsync(inValue);
        }
    }
}
