<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WebService1.asmxWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WebService1.asmxWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WebService1.asmxWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://tempuri.org/">
    <import location="https://localhost:44387/WebService1.asmx?WSDL" namespace="http://tempuri.org/"/>
    <plnk:partnerLinkType name="WebService1SoapLinkType">
        <plnk:role name="WebService1SoapRole" portType="ns:WebService1Soap"/>
    </plnk:partnerLinkType>
</definitions>
