//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RastreoCarro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class viaje
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public Nullable<bool> activo { get; set; }
        public int usuario_id { get; set; }
        public int piloto_id { get; set; }
    
        public virtual piloto piloto { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
