//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.WS_Rastreo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Rastreo.RastreoSoap")]
    public interface RastreoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplication4.WS_Rastreo.HelloWorldResponse HelloWorld(WebApplication4.WS_Rastreo.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication4.WS_Rastreo.HelloWorldResponse> HelloWorldAsync(WebApplication4.WS_Rastreo.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RastrearViajeUsuarioResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RastrearViajeUsuario", ReplyAction="*")]
        WebApplication4.WS_Rastreo.RastrearViajeUsuarioResponse RastrearViajeUsuario(WebApplication4.WS_Rastreo.RastrearViajeUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RastrearViajeUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication4.WS_Rastreo.RastrearViajeUsuarioResponse> RastrearViajeUsuarioAsync(WebApplication4.WS_Rastreo.RastrearViajeUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RastrearViajePilotoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RastrearViajePiloto", ReplyAction="*")]
        WebApplication4.WS_Rastreo.RastrearViajePilotoResponse RastrearViajePiloto(WebApplication4.WS_Rastreo.RastrearViajePilotoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RastrearViajePiloto", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication4.WS_Rastreo.RastrearViajePilotoResponse> RastrearViajePilotoAsync(WebApplication4.WS_Rastreo.RastrearViajePilotoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Rastreo.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplication4.WS_Rastreo.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Rastreo.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplication4.WS_Rastreo.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RastrearViajeUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RastrearViajeUsuario", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Rastreo.RastrearViajeUsuarioRequestBody Body;
        
        public RastrearViajeUsuarioRequest() {
        }
        
        public RastrearViajeUsuarioRequest(WebApplication4.WS_Rastreo.RastrearViajeUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RastrearViajeUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUsuario;
        
        public RastrearViajeUsuarioRequestBody() {
        }
        
        public RastrearViajeUsuarioRequestBody(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RastrearViajeUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RastrearViajeUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Rastreo.RastrearViajeUsuarioResponseBody Body;
        
        public RastrearViajeUsuarioResponse() {
        }
        
        public RastrearViajeUsuarioResponse(WebApplication4.WS_Rastreo.RastrearViajeUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RastrearViajeUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RastrearViajeUsuarioResult;
        
        public RastrearViajeUsuarioResponseBody() {
        }
        
        public RastrearViajeUsuarioResponseBody(string RastrearViajeUsuarioResult) {
            this.RastrearViajeUsuarioResult = RastrearViajeUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RastrearViajePilotoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RastrearViajePiloto", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Rastreo.RastrearViajePilotoRequestBody Body;
        
        public RastrearViajePilotoRequest() {
        }
        
        public RastrearViajePilotoRequest(WebApplication4.WS_Rastreo.RastrearViajePilotoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RastrearViajePilotoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idPiloto;
        
        public RastrearViajePilotoRequestBody() {
        }
        
        public RastrearViajePilotoRequestBody(int idPiloto) {
            this.idPiloto = idPiloto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RastrearViajePilotoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RastrearViajePilotoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Rastreo.RastrearViajePilotoResponseBody Body;
        
        public RastrearViajePilotoResponse() {
        }
        
        public RastrearViajePilotoResponse(WebApplication4.WS_Rastreo.RastrearViajePilotoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RastrearViajePilotoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RastrearViajePilotoResult;
        
        public RastrearViajePilotoResponseBody() {
        }
        
        public RastrearViajePilotoResponseBody(string RastrearViajePilotoResult) {
            this.RastrearViajePilotoResult = RastrearViajePilotoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RastreoSoapChannel : WebApplication4.WS_Rastreo.RastreoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RastreoSoapClient : System.ServiceModel.ClientBase<WebApplication4.WS_Rastreo.RastreoSoap>, WebApplication4.WS_Rastreo.RastreoSoap {
        
        public RastreoSoapClient() {
        }
        
        public RastreoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RastreoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RastreoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RastreoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication4.WS_Rastreo.HelloWorldResponse WebApplication4.WS_Rastreo.RastreoSoap.HelloWorld(WebApplication4.WS_Rastreo.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplication4.WS_Rastreo.HelloWorldRequest inValue = new WebApplication4.WS_Rastreo.HelloWorldRequest();
            inValue.Body = new WebApplication4.WS_Rastreo.HelloWorldRequestBody();
            WebApplication4.WS_Rastreo.HelloWorldResponse retVal = ((WebApplication4.WS_Rastreo.RastreoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication4.WS_Rastreo.HelloWorldResponse> WebApplication4.WS_Rastreo.RastreoSoap.HelloWorldAsync(WebApplication4.WS_Rastreo.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication4.WS_Rastreo.HelloWorldResponse> HelloWorldAsync() {
            WebApplication4.WS_Rastreo.HelloWorldRequest inValue = new WebApplication4.WS_Rastreo.HelloWorldRequest();
            inValue.Body = new WebApplication4.WS_Rastreo.HelloWorldRequestBody();
            return ((WebApplication4.WS_Rastreo.RastreoSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication4.WS_Rastreo.RastrearViajeUsuarioResponse WebApplication4.WS_Rastreo.RastreoSoap.RastrearViajeUsuario(WebApplication4.WS_Rastreo.RastrearViajeUsuarioRequest request) {
            return base.Channel.RastrearViajeUsuario(request);
        }
        
        public string RastrearViajeUsuario(int idUsuario) {
            WebApplication4.WS_Rastreo.RastrearViajeUsuarioRequest inValue = new WebApplication4.WS_Rastreo.RastrearViajeUsuarioRequest();
            inValue.Body = new WebApplication4.WS_Rastreo.RastrearViajeUsuarioRequestBody();
            inValue.Body.idUsuario = idUsuario;
            WebApplication4.WS_Rastreo.RastrearViajeUsuarioResponse retVal = ((WebApplication4.WS_Rastreo.RastreoSoap)(this)).RastrearViajeUsuario(inValue);
            return retVal.Body.RastrearViajeUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication4.WS_Rastreo.RastrearViajeUsuarioResponse> WebApplication4.WS_Rastreo.RastreoSoap.RastrearViajeUsuarioAsync(WebApplication4.WS_Rastreo.RastrearViajeUsuarioRequest request) {
            return base.Channel.RastrearViajeUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication4.WS_Rastreo.RastrearViajeUsuarioResponse> RastrearViajeUsuarioAsync(int idUsuario) {
            WebApplication4.WS_Rastreo.RastrearViajeUsuarioRequest inValue = new WebApplication4.WS_Rastreo.RastrearViajeUsuarioRequest();
            inValue.Body = new WebApplication4.WS_Rastreo.RastrearViajeUsuarioRequestBody();
            inValue.Body.idUsuario = idUsuario;
            return ((WebApplication4.WS_Rastreo.RastreoSoap)(this)).RastrearViajeUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication4.WS_Rastreo.RastrearViajePilotoResponse WebApplication4.WS_Rastreo.RastreoSoap.RastrearViajePiloto(WebApplication4.WS_Rastreo.RastrearViajePilotoRequest request) {
            return base.Channel.RastrearViajePiloto(request);
        }
        
        public string RastrearViajePiloto(int idPiloto) {
            WebApplication4.WS_Rastreo.RastrearViajePilotoRequest inValue = new WebApplication4.WS_Rastreo.RastrearViajePilotoRequest();
            inValue.Body = new WebApplication4.WS_Rastreo.RastrearViajePilotoRequestBody();
            inValue.Body.idPiloto = idPiloto;
            WebApplication4.WS_Rastreo.RastrearViajePilotoResponse retVal = ((WebApplication4.WS_Rastreo.RastreoSoap)(this)).RastrearViajePiloto(inValue);
            return retVal.Body.RastrearViajePilotoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication4.WS_Rastreo.RastrearViajePilotoResponse> WebApplication4.WS_Rastreo.RastreoSoap.RastrearViajePilotoAsync(WebApplication4.WS_Rastreo.RastrearViajePilotoRequest request) {
            return base.Channel.RastrearViajePilotoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication4.WS_Rastreo.RastrearViajePilotoResponse> RastrearViajePilotoAsync(int idPiloto) {
            WebApplication4.WS_Rastreo.RastrearViajePilotoRequest inValue = new WebApplication4.WS_Rastreo.RastrearViajePilotoRequest();
            inValue.Body = new WebApplication4.WS_Rastreo.RastrearViajePilotoRequestBody();
            inValue.Body.idPiloto = idPiloto;
            return ((WebApplication4.WS_Rastreo.RastreoSoap)(this)).RastrearViajePilotoAsync(inValue);
        }
    }
}
