//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.WS_Usuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Usuario.Actividades_UsuarioSoap")]
    public interface Actividades_UsuarioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplication4.WS_Usuario.HelloWorldResponse HelloWorld(WebApplication4.WS_Usuario.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication4.WS_Usuario.HelloWorldResponse> HelloWorldAsync(WebApplication4.WS_Usuario.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarUsuario", ReplyAction="*")]
        WebApplication4.WS_Usuario.RegistrarUsuarioResponse RegistrarUsuario(WebApplication4.WS_Usuario.RegistrarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication4.WS_Usuario.RegistrarUsuarioResponse> RegistrarUsuarioAsync(WebApplication4.WS_Usuario.RegistrarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logIn", ReplyAction="*")]
        WebApplication4.WS_Usuario.logInResponse logIn(WebApplication4.WS_Usuario.logInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logIn", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication4.WS_Usuario.logInResponse> logInAsync(WebApplication4.WS_Usuario.logInRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Origen del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PedirViaje", ReplyAction="*")]
        WebApplication4.WS_Usuario.PedirViajeResponse PedirViaje(WebApplication4.WS_Usuario.PedirViajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PedirViaje", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication4.WS_Usuario.PedirViajeResponse> PedirViajeAsync(WebApplication4.WS_Usuario.PedirViajeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento FinalizarViajeResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinalizarViaje", ReplyAction="*")]
        WebApplication4.WS_Usuario.FinalizarViajeResponse FinalizarViaje(WebApplication4.WS_Usuario.FinalizarViajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinalizarViaje", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication4.WS_Usuario.FinalizarViajeResponse> FinalizarViajeAsync(WebApplication4.WS_Usuario.FinalizarViajeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Usuario.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplication4.WS_Usuario.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Usuario.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplication4.WS_Usuario.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Usuario.RegistrarUsuarioRequestBody Body;
        
        public RegistrarUsuarioRequest() {
        }
        
        public RegistrarUsuarioRequest(WebApplication4.WS_Usuario.RegistrarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string unique;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string clave;
        
        public RegistrarUsuarioRequestBody() {
        }
        
        public RegistrarUsuarioRequestBody(string user, string tel, string unique, string clave) {
            this.user = user;
            this.tel = tel;
            this.unique = unique;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Usuario.RegistrarUsuarioResponseBody Body;
        
        public RegistrarUsuarioResponse() {
        }
        
        public RegistrarUsuarioResponse(WebApplication4.WS_Usuario.RegistrarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistrarUsuarioResult;
        
        public RegistrarUsuarioResponseBody() {
        }
        
        public RegistrarUsuarioResponseBody(bool RegistrarUsuarioResult) {
            this.RegistrarUsuarioResult = RegistrarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logIn", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Usuario.logInRequestBody Body;
        
        public logInRequest() {
        }
        
        public logInRequest(WebApplication4.WS_Usuario.logInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public logInRequestBody() {
        }
        
        public logInRequestBody(string user, string clave) {
            this.user = user;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logInResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Usuario.logInResponseBody Body;
        
        public logInResponse() {
        }
        
        public logInResponse(WebApplication4.WS_Usuario.logInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string logInResult;
        
        public logInResponseBody() {
        }
        
        public logInResponseBody(string logInResult) {
            this.logInResult = logInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PedirViajeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PedirViaje", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Usuario.PedirViajeRequestBody Body;
        
        public PedirViajeRequest() {
        }
        
        public PedirViajeRequest(WebApplication4.WS_Usuario.PedirViajeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PedirViajeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Origen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Destino;
        
        public PedirViajeRequestBody() {
        }
        
        public PedirViajeRequestBody(int idUsuario, string Origen, string Destino) {
            this.idUsuario = idUsuario;
            this.Origen = Origen;
            this.Destino = Destino;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PedirViajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PedirViajeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Usuario.PedirViajeResponseBody Body;
        
        public PedirViajeResponse() {
        }
        
        public PedirViajeResponse(WebApplication4.WS_Usuario.PedirViajeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PedirViajeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PedirViajeResult;
        
        public PedirViajeResponseBody() {
        }
        
        public PedirViajeResponseBody(string PedirViajeResult) {
            this.PedirViajeResult = PedirViajeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizarViajeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizarViaje", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Usuario.FinalizarViajeRequestBody Body;
        
        public FinalizarViajeRequest() {
        }
        
        public FinalizarViajeRequest(WebApplication4.WS_Usuario.FinalizarViajeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FinalizarViajeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUsuario;
        
        public FinalizarViajeRequestBody() {
        }
        
        public FinalizarViajeRequestBody(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizarViajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizarViajeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication4.WS_Usuario.FinalizarViajeResponseBody Body;
        
        public FinalizarViajeResponse() {
        }
        
        public FinalizarViajeResponse(WebApplication4.WS_Usuario.FinalizarViajeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FinalizarViajeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FinalizarViajeResult;
        
        public FinalizarViajeResponseBody() {
        }
        
        public FinalizarViajeResponseBody(string FinalizarViajeResult) {
            this.FinalizarViajeResult = FinalizarViajeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Actividades_UsuarioSoapChannel : WebApplication4.WS_Usuario.Actividades_UsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Actividades_UsuarioSoapClient : System.ServiceModel.ClientBase<WebApplication4.WS_Usuario.Actividades_UsuarioSoap>, WebApplication4.WS_Usuario.Actividades_UsuarioSoap {
        
        public Actividades_UsuarioSoapClient() {
        }
        
        public Actividades_UsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Actividades_UsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Actividades_UsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Actividades_UsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication4.WS_Usuario.HelloWorldResponse WebApplication4.WS_Usuario.Actividades_UsuarioSoap.HelloWorld(WebApplication4.WS_Usuario.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplication4.WS_Usuario.HelloWorldRequest inValue = new WebApplication4.WS_Usuario.HelloWorldRequest();
            inValue.Body = new WebApplication4.WS_Usuario.HelloWorldRequestBody();
            WebApplication4.WS_Usuario.HelloWorldResponse retVal = ((WebApplication4.WS_Usuario.Actividades_UsuarioSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication4.WS_Usuario.HelloWorldResponse> WebApplication4.WS_Usuario.Actividades_UsuarioSoap.HelloWorldAsync(WebApplication4.WS_Usuario.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication4.WS_Usuario.HelloWorldResponse> HelloWorldAsync() {
            WebApplication4.WS_Usuario.HelloWorldRequest inValue = new WebApplication4.WS_Usuario.HelloWorldRequest();
            inValue.Body = new WebApplication4.WS_Usuario.HelloWorldRequestBody();
            return ((WebApplication4.WS_Usuario.Actividades_UsuarioSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication4.WS_Usuario.RegistrarUsuarioResponse WebApplication4.WS_Usuario.Actividades_UsuarioSoap.RegistrarUsuario(WebApplication4.WS_Usuario.RegistrarUsuarioRequest request) {
            return base.Channel.RegistrarUsuario(request);
        }
        
        public bool RegistrarUsuario(string user, string tel, string unique, string clave) {
            WebApplication4.WS_Usuario.RegistrarUsuarioRequest inValue = new WebApplication4.WS_Usuario.RegistrarUsuarioRequest();
            inValue.Body = new WebApplication4.WS_Usuario.RegistrarUsuarioRequestBody();
            inValue.Body.user = user;
            inValue.Body.tel = tel;
            inValue.Body.unique = unique;
            inValue.Body.clave = clave;
            WebApplication4.WS_Usuario.RegistrarUsuarioResponse retVal = ((WebApplication4.WS_Usuario.Actividades_UsuarioSoap)(this)).RegistrarUsuario(inValue);
            return retVal.Body.RegistrarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication4.WS_Usuario.RegistrarUsuarioResponse> WebApplication4.WS_Usuario.Actividades_UsuarioSoap.RegistrarUsuarioAsync(WebApplication4.WS_Usuario.RegistrarUsuarioRequest request) {
            return base.Channel.RegistrarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication4.WS_Usuario.RegistrarUsuarioResponse> RegistrarUsuarioAsync(string user, string tel, string unique, string clave) {
            WebApplication4.WS_Usuario.RegistrarUsuarioRequest inValue = new WebApplication4.WS_Usuario.RegistrarUsuarioRequest();
            inValue.Body = new WebApplication4.WS_Usuario.RegistrarUsuarioRequestBody();
            inValue.Body.user = user;
            inValue.Body.tel = tel;
            inValue.Body.unique = unique;
            inValue.Body.clave = clave;
            return ((WebApplication4.WS_Usuario.Actividades_UsuarioSoap)(this)).RegistrarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication4.WS_Usuario.logInResponse WebApplication4.WS_Usuario.Actividades_UsuarioSoap.logIn(WebApplication4.WS_Usuario.logInRequest request) {
            return base.Channel.logIn(request);
        }
        
        public string logIn(string user, string clave) {
            WebApplication4.WS_Usuario.logInRequest inValue = new WebApplication4.WS_Usuario.logInRequest();
            inValue.Body = new WebApplication4.WS_Usuario.logInRequestBody();
            inValue.Body.user = user;
            inValue.Body.clave = clave;
            WebApplication4.WS_Usuario.logInResponse retVal = ((WebApplication4.WS_Usuario.Actividades_UsuarioSoap)(this)).logIn(inValue);
            return retVal.Body.logInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication4.WS_Usuario.logInResponse> WebApplication4.WS_Usuario.Actividades_UsuarioSoap.logInAsync(WebApplication4.WS_Usuario.logInRequest request) {
            return base.Channel.logInAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication4.WS_Usuario.logInResponse> logInAsync(string user, string clave) {
            WebApplication4.WS_Usuario.logInRequest inValue = new WebApplication4.WS_Usuario.logInRequest();
            inValue.Body = new WebApplication4.WS_Usuario.logInRequestBody();
            inValue.Body.user = user;
            inValue.Body.clave = clave;
            return ((WebApplication4.WS_Usuario.Actividades_UsuarioSoap)(this)).logInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication4.WS_Usuario.PedirViajeResponse WebApplication4.WS_Usuario.Actividades_UsuarioSoap.PedirViaje(WebApplication4.WS_Usuario.PedirViajeRequest request) {
            return base.Channel.PedirViaje(request);
        }
        
        public string PedirViaje(int idUsuario, string Origen, string Destino) {
            WebApplication4.WS_Usuario.PedirViajeRequest inValue = new WebApplication4.WS_Usuario.PedirViajeRequest();
            inValue.Body = new WebApplication4.WS_Usuario.PedirViajeRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.Origen = Origen;
            inValue.Body.Destino = Destino;
            WebApplication4.WS_Usuario.PedirViajeResponse retVal = ((WebApplication4.WS_Usuario.Actividades_UsuarioSoap)(this)).PedirViaje(inValue);
            return retVal.Body.PedirViajeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication4.WS_Usuario.PedirViajeResponse> WebApplication4.WS_Usuario.Actividades_UsuarioSoap.PedirViajeAsync(WebApplication4.WS_Usuario.PedirViajeRequest request) {
            return base.Channel.PedirViajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication4.WS_Usuario.PedirViajeResponse> PedirViajeAsync(int idUsuario, string Origen, string Destino) {
            WebApplication4.WS_Usuario.PedirViajeRequest inValue = new WebApplication4.WS_Usuario.PedirViajeRequest();
            inValue.Body = new WebApplication4.WS_Usuario.PedirViajeRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.Origen = Origen;
            inValue.Body.Destino = Destino;
            return ((WebApplication4.WS_Usuario.Actividades_UsuarioSoap)(this)).PedirViajeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication4.WS_Usuario.FinalizarViajeResponse WebApplication4.WS_Usuario.Actividades_UsuarioSoap.FinalizarViaje(WebApplication4.WS_Usuario.FinalizarViajeRequest request) {
            return base.Channel.FinalizarViaje(request);
        }
        
        public string FinalizarViaje(int idUsuario) {
            WebApplication4.WS_Usuario.FinalizarViajeRequest inValue = new WebApplication4.WS_Usuario.FinalizarViajeRequest();
            inValue.Body = new WebApplication4.WS_Usuario.FinalizarViajeRequestBody();
            inValue.Body.idUsuario = idUsuario;
            WebApplication4.WS_Usuario.FinalizarViajeResponse retVal = ((WebApplication4.WS_Usuario.Actividades_UsuarioSoap)(this)).FinalizarViaje(inValue);
            return retVal.Body.FinalizarViajeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication4.WS_Usuario.FinalizarViajeResponse> WebApplication4.WS_Usuario.Actividades_UsuarioSoap.FinalizarViajeAsync(WebApplication4.WS_Usuario.FinalizarViajeRequest request) {
            return base.Channel.FinalizarViajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication4.WS_Usuario.FinalizarViajeResponse> FinalizarViajeAsync(int idUsuario) {
            WebApplication4.WS_Usuario.FinalizarViajeRequest inValue = new WebApplication4.WS_Usuario.FinalizarViajeRequest();
            inValue.Body = new WebApplication4.WS_Usuario.FinalizarViajeRequestBody();
            inValue.Body.idUsuario = idUsuario;
            return ((WebApplication4.WS_Usuario.Actividades_UsuarioSoap)(this)).FinalizarViajeAsync(inValue);
        }
    }
}
