<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Actividades_Usuario.asmxWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/Actividades_Usuario.asmxWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/Actividades_Usuario.asmxWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://tempuri.org/">
    <import location="https://localhost:44388/Actividades_Usuario.asmx?WSDL" namespace="http://tempuri.org/"/>
    <plnk:partnerLinkType name="Actividades_UsuarioSoapLinkType">
        <plnk:role name="Actividades_UsuarioSoapRole" portType="ns:Actividades_UsuarioSoap"/>
    </plnk:partnerLinkType>
</definitions>
